name: PHPUnit Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Install WordPress test suite
        run: |
          mkdir -p tests/wordpress-tests-lib
          cd tests/wordpress-tests-lib
          wp core download --path=../wordpress --version=latest --force
      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml
